name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # ou o nome do seu branch principal (ex: "master", "develop")

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou outra versão que seu projeto use

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
